const jobs=[
{id:'demo-1',employer:'Example AI Labs',title:'Japanese AI Evaluator',category:'AI Trainer / Evaluator',location:'Japan',remote:'remote',japan:true,japanese:true,english:'B1',payMin:18,payMax:24,currency:'USD',period:'hour',verified:'MVP demo record',url:'#'},
{id:'demo-2',employer:'Example Localization Co.',title:'Japanese Localization Reviewer',category:'Localization',location:'Remote — APAC',remote:'remote',japan:true,japanese:true,english:'B2',payMin:22,payMax:30,currency:'USD',period:'hour',verified:'MVP demo record',url:'#'},
{id:'demo-3',employer:'Example Data Network',title:'Search Quality Rater — Japanese',category:'Search / Ads Evaluation',location:'Japan',remote:'remote',japan:true,japanese:true,english:'B1',payMin:15,payMax:20,currency:'USD',period:'hour',verified:'MVP demo record',url:'#'},
{id:'demo-4',employer:'Example Support Cloud',title:'Customer Support Specialist — Japan',category:'Customer Support',location:'Remote — Japan',remote:'remote',japan:true,japanese:true,english:'B2',payMin:20,payMax:28,currency:'USD',period:'hour',verified:'MVP demo record',url:'#'},
{id:'demo-5',employer:'Example Language Systems',title:'Japanese Language Data Annotator',category:'Data Annotation',location:'Worldwide Remote',remote:'remote',japan:true,japanese:true,english:'A2',payMin:16,payMax:21,currency:'USD',period:'hour',verified:'MVP demo record',url:'#'},
{id:'demo-6',employer:'Example Global Ops',title:'Remote Contractor — Japanese Market',category:'Remote Contractor',location:'APAC',remote:'remote',japan:true,japanese:false,english:'C1',payMin:30,payMax:45,currency:'USD',period:'hour',verified:'MVP demo record',url:'#'}
];

const $=s=>document.querySelector(s);
const state={quick:new Set()};
const ranks={A2:0,B1:1,B2:2,C1:3,C2:4};
const category=$('#category');
[...new Set(jobs.map(j=>j.category))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;category.appendChild(o)});

function payText(j){if(!j.payMin)return '報酬要確認';const max=j.payMax?`–$${j.payMax}`:'';return `$${j.payMin}${max}/${j.period==='hour'?'hr':j.period}`}
function card(j){const link=j.url==='#'?'<span class="verified">公式求人接続前のデモ表示</span>':`<a href="${j.url}" target="_blank" rel="noopener noreferrer">公式求人を見る ↗</a>`;return `<article class="job-card"><div><div class="job-top">${j.japan?'<span class="pill good">JAPAN ELIGIBLE</span>':''}${j.remote==='remote'?'<span class="pill">REMOTE</span>':''}${j.japanese?'<span class="pill">JAPANESE</span>':''}<span class="pill">${j.category}</span></div><h3>${j.title}</h3><div class="employer">${j.employer} · ${j.location}</div><div class="job-meta"><div><span>English</span> ${j.english||'—'}</div><div><span>Currency</span> ${j.currency||'—'}</div><div><span>Status</span> Preview</div></div></div><div><div class="pay">${payText(j)}</div><span class="verified">${j.verified}</span>${link}</div></article>`}

function filtered(){const q=$('#keyword').value.trim().toLowerCase();const cat=category.value;const min=Number($('#minPay').value);const eng=$('#english').value;const onlyJapan=$('#onlyJapan').checked||state.quick.has('japan');const onlyRemote=$('#onlyRemote').checked||state.quick.has('remote');return jobs.filter(j=>{if(q&&!`${j.title} ${j.employer} ${j.category}`.toLowerCase().includes(q))return false;if(cat!=='all'&&j.category!==cat)return false;if(min&&(!j.payMin||j.payMin<min))return false;if(eng!=='all'&&(ranks[j.english]??-1)<ranks[eng])return false;if(onlyJapan&&!j.japan)return false;if(onlyRemote&&j.remote!=='remote')return false;if(state.quick.has('japanese')&&!j.japanese)return false;if(state.quick.has('usd')&&j.currency!=='USD')return false;return true})}
function render(){const data=filtered();$('#jobsList').innerHTML=data.map(card).join('');$('#resultCount').textContent=data.length;$('#emptyState').hidden=data.length>0}
function metrics(){const active=jobs.length;const jp=jobs.filter(j=>j.japan).length;const remote=jobs.filter(j=>j.remote==='remote').length;const hourly=jobs.filter(j=>j.currency==='USD'&&j.period==='hour'&&j.payMin).map(j=>j.payMin);$('#metricJobs').textContent=active;$('#metricJapan').textContent=jp;$('#metricRemote').textContent=remote;$('#metricPay').textContent=hourly.length?`$${(hourly.reduce((a,b)=>a+b,0)/hourly.length).toFixed(0)}`:'—'}
['keyword','category','minPay','english','onlyJapan','onlyRemote'].forEach(id=>$('#'+id).addEventListener('input',render));
$('#searchButton').addEventListener('click',()=>{render();document.querySelector('#jobs').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{const f=btn.dataset.filter;state.quick.has(f)?state.quick.delete(f):state.quick.add(f);btn.classList.toggle('active');render()}));
$('#resetFilters').addEventListener('click',()=>{$('#keyword').value='';category.value='all';$('#minPay').value='0';$('#english').value='all';$('#onlyJapan').checked=false;$('#onlyRemote').checked=false;state.quick.clear();document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));render()});
metrics();render();