"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, Boxes, ChevronRight, CircleDollarSign, Compass, Menu, RefreshCw, Sparkles, X } from "lucide-react";
import AIWorkstyleCheck from "./ai-workstyle-check";

type Lang = "ja" | "en";
type Status = "FREE" | "PAID" | "EXTERNAL" | "HUB" | "PAUSED";
type Asset = { ja:string; en:string; jaDesc:string; enDesc:string; href?:string; status:Status; event:string; external?:boolean };
type Category = { id:string; icon:React.ReactNode; ja:string; en:string; jaLead:string; enLead:string; assets:Asset[] };

const NOTE = "https://note.com/deft_eel6718";
const STRATUM = "https://stratumpraxis.com/";

const categories:Category[] = [
  { id:"start", icon:<Compass/>, ja:"はじめる", en:"Start", jaLead:"まず無料で現在地を知る。AIの使い方と収益化の前提を短く確認。", enLead:"Start free. Understand how you use AI and test the assumptions behind monetization claims.", assets:[
    {ja:"AIの使い方・仕事スタイル診断",en:"AI Workstyle Check",jaDesc:"AIの使い方から、自分に合う次の実践ルートを選ぶ。",enDesc:"Map your AI work style and choose a practical next route.",href:"#ai-workstyle",status:"FREE",event:"free_diagnostic_open"},
    {ja:"AI実務力チェック",en:"AI Practical Check",jaDesc:"AIを仕事で使う現在地を短く確認。",enDesc:"Check your practical AI readiness in a few steps.",href:"https://ai-practical-check.pages.dev/",status:"FREE",event:"free_diagnostic_open",external:true},
    {ja:"AIで稼げる系の主張チェック",en:"AI Income Claim Check",jaDesc:"再現性・Evidence・依存条件から、強すぎる収益主張を点検。",enDesc:"Stress-test AI income claims using evidence, repeatability, and dependencies.",href:"https://stratumpraxis.com/ai-monetization-reality-check.html",status:"FREE",event:"free_claim_check_open",external:true},
  ]},
  { id:"build", icon:<Boxes/>, ja:"作る", en:"Build", jaLead:"AIアプリ、デジタル商品、スライド、Prompt。作りたいものから選ぶ。", enLead:"Build an AI app, digital product, slide system, or reusable prompt workflow.", assets:[
    {ja:"AIアプリ開発ツール選び診断",en:"AI App Builder Router 2026",jaDesc:"目的・制約からAI App Builderの選択肢を絞る。",enDesc:"Choose an AI app-building route by goal and constraints.",href:"https://payhip.com/b/LBtbr",status:"PAID",event:"paid_product_cta",external:true},
    {ja:"AIデジタル商品づくり入門セット",en:"Global Digital Product AI Starter Kit",jaDesc:"デジタル商品の企画から公開までの実践ルート。",enDesc:"A practical route from digital-product idea to launch.",href:"https://stratumpraxis.com/global-digital-product-ai-starter-kit.html",status:"PAID",event:"paid_product_cta",external:true},
    {ja:"スマホAIスライド制作システム",en:"Smartphone AI Slide Factory",jaDesc:"スマホ中心でスライド制作を回すための実践システム。",enDesc:"A phone-first workflow for producing AI-assisted slides.",href:"https://stratumpraxis.com/smartphone-ai-slide-factory.html",status:"PAID",event:"paid_product_cta",external:true},
    {ja:"再利用できるAIプロンプト設計集",en:"Prompt Systems",jaDesc:"単発Promptではなく、判断と実行を再利用できる形にする。",enDesc:"Reusable prompt operating systems for decisions and execution.",href:"https://stratumpraxis.com/prompt-systems.html",status:"HUB",event:"asset_click",external:true},
  ]},
  { id:"earn", icon:<CircleDollarSign/>, ja:"収益化する", en:"Earn", jaLead:"収益化を煽らず、検証 → 設計 → 実行の順で進める。", enLead:"Validate first, then design and execute a monetization route.", assets:[
    {ja:"AI収益化の現実チェック",en:"AI Monetization Reality Check",jaDesc:"収益主張のEvidenceと隠れた依存条件を確認。",enDesc:"Evaluate evidence and hidden dependencies behind AI income claims.",href:"https://stratumpraxis.com/ai-monetization-reality-check.html",status:"PAID",event:"paid_product_cta",external:true},
    {ja:"スマホ中心の収益化設計",en:"Smartphone Income Blueprint",jaDesc:"スマホ主体で収益化仮説を検証する設計。",enDesc:"A phone-first workflow for validating a monetization path.",href:"https://stratumpraxis.com/smartphone-income-blueprint.html",status:"PAID",event:"paid_product_cta",external:true},
    {ja:"AI収益化ツールセット",en:"AI Monetization Toolkit",jaDesc:"収益化に必要な既存ツールを目的別にまとめるHub。",enDesc:"A goal-based hub for practical monetization tools.",href:"https://stratumpraxis.com/product-router.html",status:"HUB",event:"asset_click",external:true},
    {ja:"収益につながる次の行動振り分け",en:"Revenue Router",jaDesc:"SignalやResearchを、次の収益アクションへ振り分ける。",enDesc:"Route signals and research into a concrete revenue action.",href:"https://stratumpraxis.com/revenue-router.html",status:"PAID",event:"paid_product_cta",external:true},
  ]},
  { id:"creator", icon:<Sparkles/>, ja:"販売・作品", en:"Creator", jaLead:"Creator向け販売・作品系資産の受け皿。必要なものだけ見せる。", enLead:"A focused home for creator commerce and publishing assets.", assets:[
    {ja:"画像を使った販売・収益化システム",en:"Image Commerce",jaDesc:"専用公開URL確認後に接続。既存資産は保持し、未確認リンクは出さない。",enDesc:"Route preserved. The public destination will appear only after the existing URL is verified.",status:"EXTERNAL",event:"asset_click"},
  ]},
  { id:"read", icon:<BookOpen/>, ja:"記事・知識", en:"Read", jaLead:"記事全文を抱え込まず、読む場所へ最短で送る。", enLead:"Choose what to read here, then continue on the best publishing surface.", assets:[
    {ja:"記事・作品・コンテンツの接続拠点",en:"Folio Junction",jaDesc:"Vector系記事とストック資産を、noteや関連ツールへ接続。",enDesc:"A gateway connecting Vector articles, stock assets, note, and related tools.",href:"https://stratumpraxis.com/folio-junction/",status:"HUB",event:"asset_click",external:true},
    {ja:"Vectorのnote・記事群",en:"Vector on note",jaDesc:"新着・有料・無料の記事をnoteで読む。",enDesc:"Browse current free and paid Vector articles on note.",href:NOTE,status:"EXTERNAL",event:"external_link_click",external:true},
  ]},
  { id:"return", icon:<RefreshCw/>, ja:"また戻る", en:"Return", jaLead:"毎日・週次・困った時。次に必要な場所へ戻るための入口。", enLead:"A repeat-use entrance for daily, weekly, and problem-triggered needs.", assets:[
    {ja:"再訪・回遊のための入口ゲート",en:"Return Gate",jaDesc:"必要な場所へ進み、また戻るための再訪Hub。",enDesc:"A repeat-visit hub that routes you to what matters now.",href:"https://stratumpraxis.com/return-gate/",status:"FREE",event:"return_gate_move",external:true},
    {ja:"再訪を増やす成長システム",en:"Return Gate Growth OS",jaDesc:"現在は購入導線停止中。内容確認ページのみ案内。",enDesc:"Direct checkout is currently paused; view the product information only.",href:"https://stratumpraxis.com/return-gate-growth-os.html",status:"PAUSED",event:"asset_click",external:true},
  ]},
];

const copy = {
  ja:{role:"@vector · Individual / Creator / AI Practice",title1:"AIを使う。作る。",title2:"収益につなげる。",lead:"Vector Praxis Works Hubは、個人・Creator向けのAI実践を、目的から必要な場所へ案内する非B2Bハブです。商品名を覚える必要はありません。今やりたいことから選んでください。",choose:"目的から選ぶ",read:"記事を見る",eyebrow:"VECTOR PRAXIS WORKS HUB",question:"今日は何を進めますか？",questionLead:"大きなカテゴリだけを表示します。選ぶと、その中にある必要なページだけが開きます。",freeFirst:"無料で試す",freeText:"最初からCheckoutへ押し込みません。無料診断 → 関連資産 → 必要な時だけ購入 → Return Gateで再訪、を基本にします。",close:"閉じる",open:"開く",unverified:"公開先確認中",stratum:"法人・チーム向けは Stratum Praxisへ",footer:"AIを使う。作る。収益につなげる。そして、次に必要な場所へ進める。"},
  en:{role:"@vector · Individual / Creator / AI Practice",title1:"Use AI. Build something.",title2:"Turn it into value.",lead:"Vector Praxis Works Hub is the non-B2B route map for individuals and creators. You do not need to know product names. Start with what you want to do now.",choose:"Choose by goal",read:"Browse articles",eyebrow:"VECTOR PRAXIS WORKS HUB",question:"What do you want to move forward today?",questionLead:"Only the main categories are shown first. Open one to reveal the relevant pages inside it.",freeFirst:"Start free",freeText:"No forced checkout. Start with free value, move to a relevant asset, buy only when useful, then return through Return Gate.",close:"Close",open:"Open",unverified:"Destination pending verification",stratum:"For companies and teams, go to Stratum Praxis",footer:"Use AI. Build. Monetize. Then move to the next place you actually need."}
};

function capture(event:string, props:Record<string,unknown>={}){
  try{const ph=(window as unknown as {posthog?:{capture:(e:string,p?:Record<string,unknown>)=>void}}).posthog; ph?.capture(event,{surface:"vector_works_hub",...props});}catch{}
}

export default function Home(){
  const [lang,setLang]=useState<Lang>("ja");
  const [active,setActive]=useState<string|null>(null);
  const c=copy[lang];
  const activeCategory=useMemo(()=>categories.find(x=>x.id===active)||null,[active]);

  useEffect(()=>{try{const saved=localStorage.getItem("vector-lang") as Lang|null;if(saved==="ja"||saved==="en")setLang(saved);else if((navigator.language||"").toLowerCase().startsWith("en"))setLang("en");}catch{} capture("hub_view");},[]);
  useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem("vector-lang",lang)}catch{}},[lang]);
  useEffect(()=>{document.body.style.overflow=activeCategory?"hidden":"";return()=>{document.body.style.overflow=""}},[activeCategory]);

  function openCategory(id:string){setActive(id);capture("category_select",{category:id});capture("drawer_view",{category:id});}
  function closeDrawer(){setActive(null)}
  function assetClick(asset:Asset,cat:string){capture(asset.event,{category:cat,asset:asset.en,status:asset.status,destination:asset.href||null});if(asset.href?.startsWith("#")){setActive(null);setTimeout(()=>document.querySelector(asset.href!)?.scrollIntoView({behavior:"smooth"}),60)}}

  return <main className="vw-root" id="top">
    <div className="vw-grid" aria-hidden="true"/><div className="vw-glow vw-glow-a" aria-hidden="true"/><div className="vw-glow vw-glow-b" aria-hidden="true"/>
    <header className="vw-header">
      <a href="#top" className="vw-brand"><span className="vw-mark">V</span><span><b>Vector Praxis</b><small>Works Hub</small></span></a>
      <nav className="vw-nav"><a href="#routes">Routes</a><a href="#ai-workstyle">Check</a><a href={NOTE} target="_blank" rel="noreferrer">Read</a></nav>
      <div className="vw-actions"><div className="vw-lang" role="group" aria-label="Language"><button onClick={()=>setLang("ja")} aria-pressed={lang==="ja"}>日本語</button><button onClick={()=>setLang("en")} aria-pressed={lang==="en"}>EN</button></div><button className="vw-menu" onClick={()=>openCategory("start")} aria-label="Open routes"><Menu size={18}/></button></div>
    </header>

    <section className="vw-hero vw-shell">
      <div className="vw-kicker"><span/> {c.eyebrow}</div>
      <p className="vw-role">{c.role}</p>
      <h1>{c.title1}<br/><em>{c.title2}</em></h1>
      <p className="vw-lead">{c.lead}</p>
      <div className="vw-hero-actions"><a href="#routes" className="vw-btn vw-primary">{c.choose}<ArrowRight size={17}/></a><a href={NOTE} target="_blank" rel="noreferrer" data-event="external_link_click" className="vw-btn vw-secondary">{c.read}<ArrowUpRight size={16}/></a></div>
      <div className="vw-flow" aria-label="Vector flow"><span>USE</span><i>→</i><span>BUILD</span><i>→</i><span>EARN</span><i>→</i><span>RETURN</span></div>
    </section>

    <section id="routes" className="vw-routes vw-shell">
      <div className="vw-section-head"><span>ROUTE BY INTENT</span><h2>{c.question}</h2><p>{c.questionLead}</p></div>
      <div className="vw-category-grid">{categories.map((cat,index)=><button key={cat.id} className="vw-category" onClick={()=>openCategory(cat.id)}><span className="vw-index">0{index+1}</span><span className="vw-icon">{cat.icon}</span><span className="vw-cat-copy"><b>{lang==="ja"?cat.ja:cat.en}</b><small>{lang==="ja"?cat.jaLead:cat.enLead}</small></span><ChevronRight className="vw-chevron"/></button>)}</div>
    </section>

    <section className="vw-free vw-shell"><div><span>FREE FIRST</span><h2>{c.freeFirst}</h2><p>{c.freeText}</p></div><button className="vw-btn vw-primary" onClick={()=>openCategory("start")}>{c.choose}<ArrowRight size={17}/></button></section>

    <section id="ai-workstyle" className="vw-check"><AIWorkstyleCheck/></section>

    <section className="vw-stratum vw-shell"><div><span>B2B / TEAM</span><h2>{c.stratum}</h2></div><a href={STRATUM} target="_blank" rel="noreferrer" data-event="vector_to_stratum" className="vw-btn vw-secondary">Stratum Praxis <ArrowUpRight size={16}/></a></section>

    <footer className="vw-footer vw-shell"><div className="vw-brand"><span className="vw-mark">V</span><span><b>Vector Praxis</b><small>Works Hub</small></span></div><p>{c.footer}</p><small>© 2026 Vector Praxis · @vector</small></footer>

    {activeCategory&&<div className="vw-overlay" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)closeDrawer()}}><aside className="vw-drawer" role="dialog" aria-modal="true" aria-labelledby="vw-drawer-title"><div className="vw-drawer-head"><div><span>{activeCategory.id.toUpperCase()}</span><h2 id="vw-drawer-title">{lang==="ja"?activeCategory.ja:activeCategory.en}</h2><p>{lang==="ja"?activeCategory.jaLead:activeCategory.enLead}</p></div><button onClick={closeDrawer} aria-label={c.close}><X/></button></div><div className="vw-asset-list">{activeCategory.assets.map((asset,i)=>asset.href?<a key={asset.en} href={asset.href} target={asset.external?"_blank":undefined} rel={asset.external?"noreferrer":undefined} data-event={asset.event} onClick={()=>assetClick(asset,activeCategory.id)} className="vw-asset"><span className={`vw-status s-${asset.status.toLowerCase()}`}>{asset.status}</span><span className="vw-asset-copy"><b>{lang==="ja"?asset.ja:asset.en}</b><small>{lang==="ja"?asset.jaDesc:asset.enDesc}</small></span><ArrowUpRight size={17}/></a>:<div key={asset.en} className="vw-asset vw-disabled" aria-disabled="true"><span className="vw-status s-external">{asset.status}</span><span className="vw-asset-copy"><b>{lang==="ja"?asset.ja:asset.en}</b><small>{lang==="ja"?asset.jaDesc:asset.enDesc}</small><em>{c.unverified}</em></span></div>)}</div><div className="vw-drawer-foot"><span>Vector Praxis Works Hub</span><button onClick={closeDrawer}>{c.close}</button></div></aside></div>}

    <style jsx global>{`
      :root{--vw-bg:#071019;--vw-panel:#0b1622;--vw-line:#1f3546;--vw-text:#f3f7fb;--vw-muted:#8ea1b4;--vw-cyan:#73e8ff;--vw-mint:#8dffc7;--vw-violet:#a996ff}
      html{scroll-behavior:smooth}.vw-root{min-height:100vh;background:radial-gradient(circle at 55% -20%,#153249 0,transparent 38%),linear-gradient(180deg,#071019 0%,#08131d 48%,#070d14 100%);color:var(--vw-text);position:relative;overflow:hidden}.vw-root *{box-sizing:border-box}.vw-shell{width:min(1120px,calc(100% - 42px));margin:0 auto;position:relative;z-index:2}.vw-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(115,232,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(115,232,255,.035) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(to bottom,black,transparent 72%);pointer-events:none}.vw-glow{position:absolute;border-radius:50%;filter:blur(90px);opacity:.17;pointer-events:none}.vw-glow-a{width:420px;height:420px;background:#36d6ff;top:120px;right:-140px;animation:vwFloat 12s ease-in-out infinite}.vw-glow-b{width:340px;height:340px;background:#7c5cff;top:520px;left:-180px;animation:vwFloat 15s ease-in-out infinite reverse}@keyframes vwFloat{50%{transform:translate3d(0,34px,0) scale(1.06)}}
      .vw-header{height:76px;width:min(1180px,calc(100% - 30px));margin:0 auto;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;border-bottom:1px solid rgba(143,180,205,.13);position:relative;z-index:20}.vw-brand{display:flex;align-items:center;gap:11px;color:inherit;text-decoration:none}.vw-brand span:last-child{display:grid;gap:1px}.vw-brand b{font-size:13px;letter-spacing:.04em}.vw-brand small{font-size:9px;letter-spacing:.18em;color:#7190a5;text-transform:uppercase}.vw-mark{width:32px;height:32px;border:1px solid #54d8f7;border-radius:9px;display:grid;place-items:center;font-weight:900;color:#9af0ff;box-shadow:inset 0 0 18px rgba(84,216,247,.1),0 0 22px rgba(84,216,247,.08)}.vw-nav{display:flex;gap:28px}.vw-nav a{font-size:11px;color:#8ea1b4;text-decoration:none;letter-spacing:.06em}.vw-nav a:hover{color:white}.vw-actions{display:flex;justify-content:flex-end;align-items:center;gap:10px}.vw-lang{display:flex;border:1px solid #233849;background:#09131d;border-radius:10px;padding:3px}.vw-lang button,.vw-menu{border:0;background:transparent;color:#7990a3;cursor:pointer}.vw-lang button{padding:7px 9px;border-radius:7px;font:700 10px/1 system-ui}.vw-lang button[aria-pressed=true]{background:#173044;color:#baf5ff}.vw-menu{display:none;padding:9px}
      .vw-hero{padding:94px 0 70px}.vw-kicker,.vw-role,.vw-section-head>span,.vw-free>div>span,.vw-stratum span{font-size:10px;letter-spacing:.17em;color:#7eeaff;text-transform:uppercase;font-weight:800}.vw-kicker{display:flex;align-items:center;gap:8px}.vw-kicker span{width:20px;height:1px;background:#7eeaff}.vw-role{margin:28px 0 13px;color:#6e8294}.vw-hero h1{font-size:clamp(48px,8vw,94px);line-height:.95;letter-spacing:-.055em;margin:0;max-width:900px}.vw-hero h1 em{font-style:normal;background:linear-gradient(90deg,#9df4ff,#86ffd0 52%,#b4a7ff);-webkit-background-clip:text;color:transparent}.vw-lead{max-width:690px;color:#9aabba;font-size:16px;line-height:1.85;margin:30px 0}.vw-hero-actions{display:flex;gap:10px;flex-wrap:wrap}.vw-btn{min-height:45px;padding:0 18px;border-radius:12px;display:inline-flex;align-items:center;justify-content:center;gap:9px;text-decoration:none;font-size:12px;font-weight:800;letter-spacing:.02em;border:1px solid #284358;cursor:pointer}.vw-primary{background:linear-gradient(135deg,#98f3ff,#8dffc7);color:#031018;border-color:transparent;box-shadow:0 12px 30px rgba(115,232,255,.12)}.vw-secondary{background:#0b1722;color:#dceaf2}.vw-flow{display:flex;gap:12px;align-items:center;margin-top:58px;font:800 9px/1 system-ui;letter-spacing:.15em;color:#6f8597}.vw-flow i{font-style:normal;color:#3e5b70}
      .vw-routes{padding:52px 0 96px}.vw-section-head{max-width:690px;margin-bottom:28px}.vw-section-head h2,.vw-free h2,.vw-stratum h2{font-size:clamp(28px,4vw,46px);letter-spacing:-.035em;margin:8px 0 12px}.vw-section-head p,.vw-free p{color:#8ea1b4;line-height:1.8;margin:0}.vw-category-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.vw-category{min-height:172px;text-align:left;border:1px solid #1d3446;background:linear-gradient(145deg,rgba(13,27,40,.9),rgba(8,18,28,.9));border-radius:18px;padding:20px;display:grid;grid-template-columns:auto 1fr auto;grid-template-rows:auto 1fr;gap:12px 16px;color:inherit;cursor:pointer;position:relative;overflow:hidden;transition:.2s ease}.vw-category:before{content:"";position:absolute;inset:auto -20% -70% 20%;height:120px;background:radial-gradient(circle,#37dfff25,transparent 68%);transition:.25s}.vw-category:hover{transform:translateY(-3px);border-color:#3f718c}.vw-category:hover:before{transform:translateY(-14px)}.vw-index{font:700 9px/1 system-ui;color:#53758d;letter-spacing:.14em}.vw-icon{grid-row:2;width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#102637;color:#7eeaff}.vw-icon svg{width:19px}.vw-cat-copy{grid-row:2;display:grid;align-content:start;gap:8px}.vw-cat-copy b{font-size:21px;letter-spacing:-.02em}.vw-cat-copy small{color:#8ea1b4;line-height:1.6;font-size:12px}.vw-chevron{grid-row:2;color:#56768c;align-self:center}
      .vw-free{margin-bottom:90px;padding:30px;border:1px solid #294455;border-radius:20px;background:linear-gradient(120deg,#0d1d2a,#0a1520);display:grid;grid-template-columns:1fr auto;align-items:center;gap:30px}.vw-free h2{font-size:30px}.vw-free p{max-width:680px}.vw-check{position:relative;z-index:2}.vw-stratum{margin-top:70px;margin-bottom:70px;padding:28px;border-top:1px solid #20384a;border-bottom:1px solid #20384a;display:flex;justify-content:space-between;align-items:center;gap:20px}.vw-stratum h2{font-size:25px;margin-bottom:0}.vw-footer{padding:20px 0 52px;display:grid;grid-template-columns:1fr 1fr auto;gap:24px;align-items:end;color:#6f8495}.vw-footer p{font-size:12px;line-height:1.7;margin:0}.vw-footer>small{font-size:10px}
      .vw-overlay{position:fixed;inset:0;background:rgba(2,7,11,.72);backdrop-filter:blur(8px);z-index:100;display:flex;justify-content:flex-end;animation:vwFade .18s ease}.vw-drawer{height:100%;width:min(560px,92vw);background:linear-gradient(180deg,#0c1722,#08131d);border-left:1px solid #294458;box-shadow:-20px 0 60px rgba(0,0,0,.35);padding:28px;display:flex;flex-direction:column;animation:vwSlide .26s cubic-bezier(.2,.75,.2,1)}@keyframes vwFade{from{opacity:0}}@keyframes vwSlide{from{transform:translateX(35px);opacity:.2}}.vw-drawer-head{display:grid;grid-template-columns:1fr auto;gap:20px;padding-bottom:20px;border-bottom:1px solid #1d3446}.vw-drawer-head>div>span{font-size:9px;letter-spacing:.16em;color:#6ce9ff;font-weight:900}.vw-drawer-head h2{font-size:34px;letter-spacing:-.035em;margin:7px 0}.vw-drawer-head p{font-size:12px;line-height:1.7;color:#8fa1b2;margin:0;max-width:430px}.vw-drawer-head button{width:40px;height:40px;border:1px solid #263d4e;border-radius:12px;background:#0b1620;color:#8fa5b6;display:grid;place-items:center;cursor:pointer}.vw-asset-list{display:grid;gap:9px;padding:20px 0;overflow:auto}.vw-asset{display:grid;grid-template-columns:auto 1fr auto;gap:13px;align-items:start;padding:16px;border:1px solid #1f3445;border-radius:14px;background:#0a151f;color:inherit;text-decoration:none;transition:.18s}.vw-asset[href]:hover{border-color:#3a718b;transform:translateX(-3px);background:#0d1b27}.vw-status{margin-top:2px;border:1px solid #315066;border-radius:999px;padding:5px 7px;font:900 8px/1 system-ui;letter-spacing:.08em;color:#9ccfe3}.s-free{color:#93ffd0;border-color:#285c4d}.s-paid{color:#ffe6a3;border-color:#5f5130}.s-hub{color:#bcb1ff;border-color:#504879}.s-paused{color:#ffb5a8;border-color:#674139}.vw-asset-copy{display:grid;gap:6px}.vw-asset-copy b{font-size:14px}.vw-asset-copy small{font-size:11px;color:#8ea1b4;line-height:1.55}.vw-asset-copy em{font-style:normal;font-size:9px;color:#d3a69e}.vw-disabled{opacity:.62}.vw-drawer-foot{margin-top:auto;padding-top:16px;border-top:1px solid #1d3446;display:flex;justify-content:space-between;align-items:center;color:#668195;font-size:10px}.vw-drawer-foot button{border:0;background:transparent;color:#a6bac9;cursor:pointer}
      @media(max-width:760px){.vw-shell{width:min(100% - 28px,1120px)}.vw-header{height:68px;grid-template-columns:1fr auto;width:calc(100% - 24px)}.vw-nav{display:none}.vw-menu{display:grid}.vw-hero{padding:68px 0 48px}.vw-hero h1{font-size:clamp(45px,14vw,68px)}.vw-lead{font-size:14px}.vw-flow{overflow:auto;padding-bottom:4px}.vw-category-grid{grid-template-columns:1fr}.vw-category{min-height:150px}.vw-free{grid-template-columns:1fr;padding:22px}.vw-stratum{align-items:flex-start;flex-direction:column}.vw-footer{grid-template-columns:1fr;align-items:start}.vw-overlay{align-items:flex-end}.vw-drawer{width:100%;height:min(82vh,760px);border-left:0;border-top:1px solid #2b475b;border-radius:22px 22px 0 0;padding:20px;animation:vwSheet .26s cubic-bezier(.2,.75,.2,1)}@keyframes vwSheet{from{transform:translateY(45px);opacity:.2}}.vw-drawer-head h2{font-size:28px}.vw-asset{grid-template-columns:auto 1fr}.vw-asset>svg{display:none}}
      @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.vw-glow{animation:none}.vw-category,.vw-asset,.vw-drawer,.vw-overlay{animation:none;transition:none}}
    `}</style>
  </main>
}
