import { ArrowUpRight, BookOpen, Compass, FileText, Layers3 } from "lucide-react";
import MotionEnhancer from "./motion-enhancer";
const NOTE = "https://note.com/deft_eel6718";
const MAGAZINE = "https://note.com/deft_eel6718/m/md4fd3d914fe5";
const resources = [
  { label:"無料記事", title:"AIでSEO記事作成を効率化するなら、\n「書く」より先に見直したい5つの工程", description:"記事制作を、キーワード・構成・執筆・確認・入稿までの工程として整理します。", href:"https://note.com/deft_eel6718/n/n86dddd12d2b2", event:"article_open" },
  { label:"有料記事 · ¥1,980", title:"AIアプリ開発に月額課金する前に｜\n無料AIビルダー使い分け完全ガイド 2026", description:"無料・有料AIビルダーの違いと、課金すべきタイミングを整理する実践ガイドです。", href:"https://note.com/deft_eel6718/n/n7574edd94a5b?app_launch=false", event:"product_click" },
  { label:"有料記事 · ¥1,980", title:"AIで作るだけでは稼げない。\nAIを「収益パイプ」に変える実践設計", description:"需要、入口、無料価値、収益化、計測をひとつの流れとして設計するための実践記事です。", href:"https://note.com/deft_eel6718/n/nc120a3159186", event:"product_click" },
  { label:"有料記事 · ¥2,980", title:"不安は再生される", description:"不安を増幅するコンテンツの構造を読み解き、行動へ変える判断の枠組みを扱います。", href:"https://note.com/deft_eel6718/n/nee032c683c27", event:"product_click" },
  { label:"有料記事 · ¥9,950 · 割引表示あり", title:"Codexを「実装部隊」にして、\n広告費0円から外貨収益を作る一人会社の設計書", description:"制作で終わらせず、商品・導線・公開・計測をつなぐ一人運営の設計を扱います。", href:"https://note.com/deft_eel6718/n/n6643ede87ad3", event:"product_click" },
];
function TrackedLink({href,event,children,className="",...rest}:{href:string;event:string;children:React.ReactNode;className?:string;[key:string]:unknown}) { return <a href={href} target="_blank" rel="noopener noreferrer" data-event={event} className={className} {...rest}>{children}</a>; }
export default function Home(){return <main><MotionEnhancer/>
  <header className="site-header"><a href="#top" className="brand" aria-label="Vector Praxis ホーム"><span className="brand-mark" aria-hidden="true">VP</span><span>Vector Praxis</span></a><nav aria-label="メインナビゲーション"><a href="#start">はじめる</a><a href="#articles">記事</a><a href="#products">商品</a></nav></header>
  <section id="top" className="hero shell"><div className="eyebrow"><span/> STRUCTURE INTO PRACTICE</div><h1>複雑な情報を、<br/><em>使える構造</em>へ。</h1><p className="hero-copy">Vector Praxisは、AI・構造思考・知識整理を、実務と収益設計へつなげる日本語プロジェクトです。読むだけで終わらず、次の判断と行動が見える形に整理します。</p><div className="hero-actions"><TrackedLink href="https://note.com/deft_eel6718/n/n86dddd12d2b2" event="hub_cta_click" className="button primary">無料記事からはじめる <ArrowUpRight size={17}/></TrackedLink><TrackedLink href={NOTE} event="article_open" className="button secondary">記事一覧を見る</TrackedLink></div><div className="hero-index" aria-label="Vector Praxisの領域"><span>01 <b>構造を読む</b></span><span>02 <b>判断を整える</b></span><span>03 <b>実装へつなぐ</b></span></div></section>
  <section id="start" className="section shell"><div className="section-heading"><p>START HERE</p><h2>何をしたいですか？</h2></div><div className="route-grid"><TrackedLink href="https://note.com/deft_eel6718/n/n86dddd12d2b2" event="article_open" className="route-card"><Compass/><span><b>AIと仕事の進め方を見直す</b><small>無料記事で、改善すべき工程をつかむ</small></span><ArrowUpRight/></TrackedLink><TrackedLink href={MAGAZINE} event="article_open" className="route-card"><Layers3/><span><b>収益導線を構造から学ぶ</b><small>テーマ別にまとまったマガジンへ</small></span><ArrowUpRight/></TrackedLink><TrackedLink href={NOTE} event="article_open" className="route-card"><BookOpen/><span><b>すべての記事から探す</b><small>Vector Praxisのnote記事一覧へ</small></span><ArrowUpRight/></TrackedLink></div></section>
  <section className="section muted-section"><div className="shell tool-empty"><div className="section-heading"><p>FREE TOOLS / DIAGNOSTICS</p><h2>無料ツール・診断</h2></div><div className="empty-panel"><span className="status-dot"/><div><b>公開確認できるVector Praxis名義の無料ツールは、現在このHubには掲載していません。</b><p>未確認のリンクを載せず、まずは検証済みの無料記事を入口にしています。公開状態を確認できたツールから順次追加します。</p></div><TrackedLink href="https://note.com/deft_eel6718/n/n86dddd12d2b2" event="tool_open" className="text-link">無料記事を読む <ArrowUpRight size={15}/></TrackedLink></div></div></section>
  <section id="articles" className="section shell"><div className="section-heading split"><div><p>ARTICLES / PRODUCTS</p><h2>読みたい深さから選ぶ</h2></div><TrackedLink href={NOTE} event="article_open" className="text-link">noteですべて見る <ArrowUpRight size={15}/></TrackedLink></div><div className="resource-list">{resources.map((item,index)=><article className="resource" key={item.href} id={index===1?"products":undefined}><div className="resource-no">0{index+1}</div><div className="resource-main"><span className="tag">{item.label}</span><h3>{item.title.split("\n").map(line=><span key={line}>{line}<br/></span>)}</h3><p>{item.description}</p></div><TrackedLink href={item.href} event={item.event} className="round-link" aria-label={`${item.title}を開く`}><ArrowUpRight/></TrackedLink></article>)}</div><p className="price-note">価格・割引表示は2026年8月27日の公開ページ確認時点。購入前にnote上の最新表示をご確認ください。</p></section>
  <section className="section path-section"><div className="shell path-layout"><div className="section-heading"><p>RECOMMENDED PATH</p><h2>迷ったら、この順序で。</h2></div><ol className="path"><li><span>01</span><b>無料で読む</b><small>考え方との相性を確認</small></li><li><span>02</span><b>課題を特定</b><small>どこが詰まっているか整理</small></li><li><span>03</span><b>深く学ぶ</b><small>必要なテーマだけ購入</small></li><li><span>04</span><b>実務へ戻す</b><small>記事を判断と実装に使う</small></li></ol></div></section>
  <section className="section shell return-panel"><FileText size={26}/><div><p>RETURN LOOP</p><h2>新しい記事と整理された実践知を、ここから。</h2><span>新しい公開資産は、確認後にこのHubへ接続します。ブックマークして、必要なときに戻ってきてください。</span></div><TrackedLink href={NOTE} event="article_open" className="button secondary">最新記事を確認</TrackedLink></section>
  <footer className="footer shell"><div><span className="brand-mark">VP</span><b>Vector Praxis</b></div><p>AI・構造思考・知識整理を、実務と収益設計へ。</p><nav aria-label="フッターナビゲーション"><TrackedLink href={NOTE} event="article_open">note</TrackedLink><TrackedLink href={MAGAZINE} event="article_open">マガジン</TrackedLink></nav><small>© 2026 Vector Praxis</small></footer>
  <script dangerouslySetInnerHTML={{__html:`document.addEventListener('click',function(e){var a=e.target.closest('[data-event]');if(!a)return;var n=a.dataset.event;var d={event:n,link_url:a.href,link_text:(a.innerText||'').trim().slice(0,100)};window.dataLayer=window.dataLayer||[];window.dataLayer.push(d);if(typeof window.gtag==='function')window.gtag('event',n,d)});window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'hub_view'});if(typeof window.gtag==='function')window.gtag('event','hub_view');`}}/>
 </main>}
